# Generated by Django 3.2.12 on 2022-03-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos_olimpicos', '0002_evento_atleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='season',
            field=models.CharField(blank=True, choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=6, null=True),
        ),
    ]
