# Generated by Django 3.2.12 on 2022-04-03 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos_olimpicos', '0003_alter_evento_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOC_team',
            fields=[
                ('noc', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('team', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='noc',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='team',
        ),
        migrations.AddField(
            model_name='atleta',
            name='noc_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogos_olimpicos.noc_team'),
        ),
    ]
